drive_node:
  ros__parameters:
    speed_motor: 255.0

command_node:
  ros__parameters:
    box_pos_1: 5000.0
    box_pos_2: 10000.0
    box_pos_3: 15000.0
    box_pos_4: 20000.0
    box_pos_5: 25000.0
